name:                haskellgame
version:             3.0.0.0
author:              "Pavel Yeltsin"
copyright:           "2019 Pavel Yeltsin"

extra-source-files:
- README.md

description:         Please see the README file.

dependencies:
- base >= 4.7 && < 5
- gloss
- containers
- data-default
- pqueue

library:
  source-dirs: src

executables:
  game:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellgame

tests:
  game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellgame
